/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { YcombinatorApi } from "@fern-api/ycombinator";
import * as core from "../../../../core";

export const Company: core.serialization.ObjectSchema<serializers.Company.Raw, YcombinatorApi.Company> =
    core.serialization.object({
        id: core.serialization.number(),
        name: core.serialization.string(),
        slug: core.serialization.string(),
        website: core.serialization.string(),
        smallLogoUrl: core.serialization.string(),
        oneLiner: core.serialization.string(),
        longDescription: core.serialization.string(),
        teamSize: core.serialization.number(),
        url: core.serialization.string(),
        batch: core.serialization.string(),
        tags: core.serialization.list(core.serialization.string()),
        status: core.serialization.string(),
        industries: core.serialization.list(core.serialization.string()),
        regions: core.serialization.list(core.serialization.string()),
        locations: core.serialization.list(core.serialization.string()),
        badges: core.serialization.list(core.serialization.unknown()),
    });

export declare namespace Company {
    interface Raw {
        id: number;
        name: string;
        slug: string;
        website: string;
        smallLogoUrl: string;
        oneLiner: string;
        longDescription: string;
        teamSize: number;
        url: string;
        batch: string;
        tags: string[];
        status: string;
        industries: string[];
        regions: string[];
        locations: string[];
        badges: unknown[];
    }
}
