/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class YcombinatorApiTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, YcombinatorApiTimeoutError.prototype);
    }
}
