/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetAllCompaniesRequest {
    /**
     * You can page through responses with a page parameter
     */
    page?: number;
    /**
     * To search YC companies, you can pass in a general search query.
     */
    q?: string;
    /**
     * The batch the company participated in
     */
    batch?: string;
    /**
     * The status of the company
     */
    status?: string;
    /**
     * The industry of the company
     */
    industry?: string;
    /**
     * The region of the company
     */
    region?: string;
    /**
     * The tags self-selected by the company
     */
    tags?: string;
    /**
     * Whether or not the company is actively hiring
     */
    isHiring?: boolean;
    /**
     * Whether or not the company is a non-profit
     */
    nonprofit?: boolean;
    /**
     * Whether or not the company has self-selected as having a black founder
     */
    highlightBlack?: boolean;
    /**
     * Whether or not the company has self-selected as having a latinx founder
     */
    highlightLatinx?: boolean;
    /**
     * Whether or not the company has self-selected as having a female founder
     */
    highlightWomen?: boolean;
}
