/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { YcombinatorApi } from "@fern-api/ycombinator";

export interface AllCompanies {
    companies: YcombinatorApi.Company[];
    page: number;
    totalPages: number;
}
