/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type Status = "Active" | "Public" | "Acquired" | "Inactive";

export const Status = {
    Active: "Active",
    Public: "Public",
    Acquired: "Acquired",
    Inactive: "Inactive",
} as const;
