/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const YcombinatorApiEnvironment = {
    Production: "https://api.ycombinator.com/v0.1",
} as const;

export type YcombinatorApiEnvironment = typeof YcombinatorApiEnvironment.Production;
